### ISSUE TITLE
Can't match domains like 17173.com

### ISSUE THREAD

**Issue by donilan** [amol9/imagebot#1]
Hello, You creating a great software. 

It's works great but when I trying to crawl some website like 17173.com which domain starts with number, it wouldn't works.

I found the problem is in the submodule "web", the regex that in class AbsUrl would not match such domains. Could you change it for me? Thanks.

**Comment by amol9** [comment]
Hi,
Thanks for reporting the issue.

I have fixed the regex for url. Although, now, the module 'web' is part of the package 'mutils' (on pypi). If you download and install imagebot(v1.2.1), you should not see this issue.

Regards,
Amol.
